version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  say-bye:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say bye"
          command: "echo Bye, World!"

  setup-failure:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Simulate setup failure"
          command: "exit 1"

workflows:
  running-workflow:
    jobs:
      - say-hello
      - say-bye:
          requires:
            - say-hello

  failing-workflow:
    jobs:
      - say-hello
      - setup-failure
      - say-bye:
          requires:
            - setup-failure

  canceled-workflow:
    jobs:
      - say-hello
      - setup-failure
      - say-bye:
          requires:
            - setup-failure

  on-hold-workflow:
    jobs:
      - say-hello
      - setup-failure
      - say-bye:
          requires:
            - setup-failure

  success-workflow:
    jobs:
      - say-hello
      - say-bye:
          requires:
            - say-hello

  needs-setup-workflow:
    jobs:
      - setup-failure
